<?php
function groceries_menu() {
    $items = array();
    $items['grocery_list'] = array(
        'title' => 'Grocery List',
        'page callback' => 'show_groceries',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function show_groceries() {
    $items = array(
        'eggs' => array(
            'title' => 'eggs',
            'price' => 1.99,
            'quantity' => 2,
        ),
        'milk' => array(
            'title' => 'milk',
            'price' => 2.39,
            'quantity' => 3,
        ),
        'cookies' => array(
            'title' => 'cookies',
            'price' => 4.50,
            'quantity' => 100,
        ),
    );
    // return '<h2>Grocery List:</h2>';
    $output = null;
    foreach ($items as $food) {
        $output .= '<ul>
                        <h3>' . 'Item : ' . $food['title'] . '</h3>
                        <li>' . 'Price : ' . $food['price'] . '</li>
                        <li>' . 'Quantity : ' . $food['quantity'] . '</li>
                  </ul>';
    }
    return $output;
}
