<?php
function pet_menu() {
    $items = array();
    $items['best_pet'] = array(
        'title' => 'Fluffy',
        'page callback' => 'all_pet',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;

}
function all_pet() {
    return '<a href="https://www.youtube.com/watch?v=u5ylz0c2QB4"><img src="sites/all/img/cats_attack.jpg" alt="cats attack" /></a>';
}
